title: "Kuku"
description: "Statistics | Data Analysis & Predictive Modeling"
url: "https://kuku0508.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "air"

locale: "zh-TW"
timezone: "Asia/Taipei"

author:
  name: "kuku"
  avatar: "/assets/img/avatar.png"
  bio: |
    淡江大學 統計與資料科學學系  
    資料分析  
    資料預測