title: "Kuku"
description: "Portfolio and article notes on data analysis, modeling, and visualization"
url: "https://kuku0508.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "air"

locale: "zh-TW"
timezone: "Asia/Taipei"

author:
  name: "kuku"
  avatar: "/assets/img/avatar.png"
  url: "https://kuku0508.github.io"
  bio: |
    淡江大學 統計與資料科學學系  
    資料分析  
    資料預測
  github: "https://github.com/kuku0508"
  instagram: "https://www.instagram.com/kuku_0508_?igsh=MTNoNGpoZXM4NmF5bw%3D%3D&utm_source=qr"
  linkedin: "https://www.linkedin.com/in/hsu-chang/?trk=public-profile-join-page"
  email: "kuku050812@gmail.com"
  favorite_color: "#ffb3c6"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
